### PR TITLE
#361: fixing the partitioning checkpoint (not paginated) API endpoint

### LINKED ISSUE #361: Endpoint GET /api/v2/partitionings/{{partitioning_id}}/checkpoints/{{checkpoint_id}} not working
## Describe the bug

Wrong datatype, used in 2 places, redundant `hasMore` attribute of case class, wrong mapping, makes the whole endpoint disfunctional:
* GET `/api/v2/partitionings/{{partitioning_id}}/checkpoints/{{checkpoint_id}}`

check file `CheckpointItemFromDB.scala` and especially `hasMore: Boolean` attribute. The class in question is used in 2 places, i.e. for 2 endpoints, one is using this `hadMore` (and is working fine) and the other is not (and is not working at all). We need to fix this issue. 

## To Reproduce
Just run this endpoint, it will return this:

```
{
    "message": "Failed to perform 'getCheckpoint': Operation 'getCheckpoint' failed with unexpected error: The column index is out of range: 12, number of columns: 11.",
    "requestId": "f1c1258b-2510-49ff-b88a-9b85a5ce50ac"
}
```

## Expected behavior
The endpoint works.

### PR DESCRIPTION
**Pull request by lsulak**
Release Notes:
* Fixed `GET /api/v2/partitionings/{partitioningId}/checkpoints/{checkpointId}` API endpoint

Closes #361

### CODE REVIEW

File: server/src/main/scala/za/co/absa/atum/server/model/database/CheckpointItemFromDB.scala [hunk 1]
```diff
@@ -22,21 +22,45 @@ import za.co.absa.atum.model.dto.{CheckpointV2DTO, MeasureDTO, MeasureResultDTO,
...
 object CheckpointItemFromDB {
 
+  case class NotPaginated(
+    override val idCheckpoint: UUID,
+    override val checkpointName: String,
+    override val author: String,
+    override val measuredByAtumAgent: Boolean,
+    override val measureName: String,
+    override val measuredColumns: Seq[String],
+    override val measurementValue: Json, // JSON representation of `MeasurementDTO`
```
Comment (salamonpavel) [inline server/src/main/scala/za/co/absa/atum/server/model/database/CheckpointItemFromDB.scala:46]: I guess we don't need to mention this three times.

**Review by salamonpavel — APPROVED** [review]
