### PR TITLE
PartitioningUpdateException

### LINKED ISSUE #261: AtumPartition.subPartitionContext orders partition keys differently in Scala 2.12 vs Scala 2.13
## Describe the bug
When I create a sub-partition, the order of the partition keys are different across Scala version 2.12 and 2.13, as they get combined with the parent partition's keys. This is probably because of a different behaviour in the `++` operator of `ListMap`.

It's not exactly clear to me, if this is a bug, or if the ordering of the partition keys is not relevant.

## To Reproduce
Steps to reproduce the behavior OR commands run:
Using AtumAgent v0.2.0, execute the following commands:
```
    val rawCtx = AtumAgent.getOrCreateAtumContext(AtumPartitions(
      List[(String, String)](
        "source_system" -> "test_system",
        "dataset_name" -> "test_pipeline",
        "info_date" -> "2024-08-30"
      )
    ))
    val publishCtx = rawCtx.subPartitionContext(AtumPartitions(
      List[(String, String)](
        "catalog_path" -> "test_db.test_pipeline",
        "info_date" -> "2024-08-30"
      )
    ))
```

In Scala 2.12 `publishCtx.atumPartitions` is
```
List(
  PartitionDTO("source_system", "test_system"),
  PartitionDTO("dataset_name", "test_pipeline"),
  PartitionDTO("catalog_path", "test_db.test_table"),
  PartitionDTO("info_date", "2024-08-30")
)
```

However, in Scala 2.13, it is
```
List(
  PartitionDTO("source_system", "test_system"),
  PartitionDTO("dataset_name", "test_pipeline"),
  PartitionDTO("info_date", "2024-08-30"),
  PartitionDTO("catalog_path", "test_db.test_table")
)
```

The issue seems to be a different behaviour of the `++` operator in ListMap between Scala 2.12 and 2.13.

A similar example is the following code:
```
import scala.collection.immutable.ListMap
val countryCapitals1: ListMap[String, String] = ListMap(
    "Canada" -> "Ottawa",
    "India" -> "Delhi"
  );

val countryCapitals2: ListMap[String, String] = ListMap(
  "Cuba" -> "Havana",
  "India" -> "New Delhi"
);

val combinedCountryCapitals = countryCapitals1 ++ countryCapitals2

println("combinedCountryCapitals:")
combinedCountryCapitals.foreach { entry =>
  print("country: " + entry._1)
  println(", capital: " + entry._2)
};
```

When executed in Scala 2.12.19, the output is
```
combinedCountryCapitals:
country: Canada, capital: Ottawa
country: Cuba, capital: Havana
country: India, capital: New Delhi
```

However, in 2.13.14, it is
```
combinedCountryCapitals:
country: Canada, capital: Ottawa
country: India, capital: New Delhi
country: Cuba, capital: Havana
```

## Expected behavior
The order should be the same across Scala 2.12 and 2.13 (unless ordering in partition keys is not relevant anymore)

### PR DESCRIPTION
**Pull request by salamonpavel**
Fixes sub partitions context creation.
Fixes #261

### CODE REVIEW

**Comment by salamonpavel** [comment]
Release notes:

- Fixes sub partitions context creation

File: agent/src/main/scala/za/co/absa/atum/agent/AtumContext.scala [hunk 1]
```diff
@@ -52,7 +53,14 @@ class AtumContext private[agent] (
    * @return the sub-partition context
    */
   def subPartitionContext(subPartitions: AtumPartitions): AtumContext = {
-    agent.getOrCreateAtumSubContext(atumPartitions ++ subPartitions)(this)
+    val newPartitions = subPartitions.foldLeft(atumPartitions) { case (acc, (k, v)) =>
```
Comment (benedeki) [inline agent/src/main/scala/za/co/absa/atum/agent/AtumContext.scala:56]: Just an idea. Wouldn't intersection be clearer, what's being checked?
```scala
val overlap = atumPartitions.keys.intersect(subPartitions.keys)
if (overlap.nonEmpty) {
  throw PartitioningUpdateException(s"Partition keys '$overlap' already exist. Updates are not allowed.")
}
```

Comment (salamonpavel) [reply agent/src/main/scala/za/co/absa/atum/agent/AtumContext.scala]: okok, refactored

**Review by benedeki — APPROVED** [review]
